Card initial support
hansemannn/titanium-material pull request #1
Opened 2018-04-23 10:06 UTC by Brianggalvez

2018-04-23 11:04 UTC, hansemannn requested changes
Left a few review comments. Can you also add a reference to the readme and an example (if possible)?

2018-04-23 11:04 UTC, hansemannn commented on titanium-material.xcodeproj/xcuserdata/Brian.xcuserdatad/xcschemes/xcschememanagement.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Remove

2018-04-23 11:04 UTC, hansemannn commented on Classes/TiMaterialCardViewProxy.m
> +    [[(TiMaterialCardView *)[self view] cardView] setContentView:[viewProxy view]];
Does the layouting work properly? I would assume that some auto-sizing does not work out of the box.

2018-04-23 11:04 UTC, hansemannn commented on Classes/TiMaterialCardView.m
> +        _cardView = [[Card alloc]initWithFrame:self.bounds];
`[[Card alloc] initWithFrame: [super bounds]];`

2018-04-23 11:04 UTC, hansemannn commented on Classes/TiMaterialCardView.m
> +
Remove blank line

2018-04-25 10:02 UTC, hansemannn commented
Fixed the issues myself and will update some additional code snippets after merging. PR **approved**!

2018-04-25 10:02 UTC, hansemannn approved these changes

2018-04-25 10:02 UTC, merged

2018-04-25 10:26 UTC, hansemannn commented
@Brianggalvez I just tested it and unfortunately it does not work in any case. Did you try your changes before submitting the PR? I may need to revert the merge.

2018-04-25 10:30 UTC, Brianggalvez commented
Hi Hans, this is my working test code without your changes 
`var card = Material.createCardView({
  height: 200,
  width: 300,
  backgroundColor: "#eceded"
});
card.setContentView(Ti.UI.createView({
  height: 50,
  width: 50,
  backgroundColor: 'red'
}));
win.add(card);
`
![simulator screen shot - iphone 7 plus - 2018-04-25 at 12 30 13](https://user-images.githubusercontent.com/18324872/39240562-6aaec498-4884-11e8-80e2-d244dea59fb9.png)

2018-04-25 10:33 UTC, hansemannn commented
Okay, then the sizing is indeed broken (with and without my changes). The width is not respected properly.

2018-04-25 10:36 UTC, Brianggalvez commented
Exactly, but I'm not sure that even the card is fully working as it doesn't inherits either backgroundColor nor borderRadius as in the example there isn't any explicit set of these. [Sample](uhttps://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/Card/Card/ViewController.swift)

2018-04-25 10:45 UTC, hansemannn commented
Ok, so it seems like the width is determined by the card-view and the height by the content view. So the content view automatically fills the card view container as well. I have exposed the `backgroundColor` property, which sets the native color on the `Card` instead of the view proxy, enabling proper a corner radius handling (which is also already exposed). I will push an updated sample soon.